// Module included in the following assemblies:
// * extensions/catalogs/olmv1-catalog-content-resolution.adoc

:_mod-docs-content-type: REFERENCE

[id="olmv1-catalog-exclusion-by-labels-or-expressions_{context}"]
= Catalog exclusion by labels or expressions

You can exclude catalogs by using match expressions on metadata with the `NotIn` or `DoesNotExist` operators.

The following cluster catalog CR adds the `example.com/testing` label to the `unwanted-catalog` cluster catalog:

.Example cluster catalog CR
[source,yaml]
----
apiVersion: olm.operatorframework.io/v1
kind: ClusterCatalog
metadata:
  name: unwanted-catalog
  labels:
    example.com/testing: "true"
spec:
  source:
    type: Image
    image:
      ref: quay.io/example/content-management-a:latest
----

The following cluster extension CR excludes selection from the `unwanted-catalog` catalog:

.Example cluster extension CR that excludes a specific catalog
[source,yaml]
----
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: <example_extension>
spec:
  namespace: <example_namespace>
  serviceAccount:
    name: <example_extension>-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: <example_extension>-operator
      selector:
        matchExpressions:
          - key: olm.operatorframework.io/metadata.name
            operator: NotIn
            values:
              - unwanted-catalog
----

The following cluster extension CR selects from catalogs that do not have the `example.com/testing` label:

.Example cluster extension CR that excludes catalogs with a specific label
[source,yaml]
----
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: <example_extension>
spec:
  namespace: <example_namespace>
  serviceAccount:
    name: <example_extension>-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: <example_extension>-operator
      selector:
        matchExpressions:
          - key: example.com/testing
            operator: DoesNotExist
----
